tab_spaces = 2
max_width = 100
newline_style = "Unix"
fn_brace_style = "SameLineWhere"
fn_single_line = true
fn_args_layout = "Visual"
where_layout = "HorizontalVertical"
struct_trailing_comma = "Never"
struct_lit_trailing_comma = "Never"
enum_trailing_comma = false
match_block_trailing_comma = false
write_mode = "Overwrite"
